services:
  - type: web
    name: fpl-data-fetcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn FplLeague:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
