apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: gcr.io/YOUR_PROJECT_ID/your-app-image
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  googleCloudBuild:
    projectId: YOUR_PROJECT_ID
